<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_editar</name>
   <tag></tag>
   <elementGuidId>17f8013c-7e19-4a30-9913-2445ddc010f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;rt-tbody&quot;]/div/div/div[text()='${firstName}']/parent::div/div/div/span[@title=&quot;Edit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
